name: Deploy to SharePoint Online

on:
  push:
    branches:
      - dev # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build React application
        run: npm run build

      - name: Deploy to SharePoint Online
        env:
          SP_CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
          SP_CLIENT_SECRET: ${{ secrets.SP_CLIENT_SECRET }}
          SP_SITE_URL: ${{ secrets.SP_SITE_URL }}
          SP_LIBRARY_PATH: "SiteAssets/Build" # Change this to your destination folder path
        run: |
          npm install -g @pnp/office365-cli
          office365 login --authType password --userName $SP_CLIENT_ID --password $SP_CLIENT_SECRET
          office365 spo login $SP_SITE_URL
          office365 spo upload --path "./build" --libraryPath $SP_LIBRARY_PATH --force

